#!/bin/bash
docker build  \
    --build-arg=http_proxy=${http_proxy} \
    --build-arg=https_proxy=${https_proxy} \
    --rm -t  ubs/build-time-env:latest . 

if [ "X$#" == "X1" ] ; then 
    echo "tagging with: $1"
    docker tag  ubs/build-time-env:latest ubs/build-time-env:latest:$1
fi
